language: ruby
cache: bundler

os:
  - linux

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - rbx-2

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "obDgAOA7J+j78ks0qmwJokIeHqvdvQRD+YEfOSOv+Xu8+a17xaX1z5SusqLAug4KTZQOoMiGq5mfVQVDTeIijqehVaNGXxnnATnKocJTcjuGiR/7JCdeJFKyQDG5Qn3udpPFQ/nqNq1URbdTGC68fUzMAwDNdvqfDhCG04yb5O8="
    - COVERITY_SCAN_PROJECT_NAME="libgit2/rugged"
    - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="schreiber.arthur@gmail.com"
    - COVERITY_SCAN_BUILD_COMMAND="bundle exec rake compile"

addons:
  apt:
    packages:
    - cmake
    - libssh2-1-dev
    - openssh-client
    - openssh-server

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
  include:
    - rvm: 2.3.0
      env: COVERITY=1
      os: linux
    - os: osx
      rvm: 2.0.0
    - os: osx
      rvm: 2.1.5
    - os: osx
      rvm: 2.2.2
    - os: osx
      rvm: rbx-2

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./vendor/libgit2/script/install-deps-osx.sh; fi
  - if [ "$COVERITY" = "1" ]; then curl -s https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh | bash; fi

script: if [ "$COVERITY" != 1 ]; then script/travisbuild; fi
